"""色設定"""

from colors import \
    PALE_GRAY, BRIGHT_GRAY, BRIGHT_GREEN, SOFT_GRAY, SOFT_RED, SOFT_BLUE, BLACK

BACKGROUND_COLOR = PALE_GRAY
GRID_COLOR = BRIGHT_GRAY
LINE_COLOR = SOFT_GRAY
FONT_COLOR = BLACK
START_COLOR = SOFT_RED
GOAL_COLOR = SOFT_BLUE
AGENT_COLOR = BRIGHT_GREEN
CHECKED_FORWARD_COLOR = START_COLOR
CHECKED_BACKWARD_COLOR = GOAL_COLOR
